name = "packwiz Create Pack"
author = "BaiYang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7339479408e7b86675ea65fb63950534c30f0e3baa5971221c92a8947dbe115"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
