name = "packwiz Create Pack"
author = "BaiYang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea49847c223dbb2c5dabbf340614e304f7aa0c50b82dfb2eb361f3373f01ba80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
