name = "packwiz Create Pack"
author = "BaiYang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3163450a55516450cd3cbb7c923e5474c16ab40bb117860d6c1a16be24783c90"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
